### ISSUE TITLE
Some extension icons are not visible in the address bar

### ISSUE THREAD

**Issue by sivapvarma** [ideaweb/firefox-safari-style#10]
github master on Firefox nightly

![](https://i.imgur.com/KsiUT2m.png)

vs Stock Firefox 76

![](https://i.imgur.com/b7dwgx8.png)

Extension in question is the [side-view extension from Mozilla](https://github.com/mozilla/side-view/).

**Comment by ideaweb** [comment]
Fixed... please update.

**Comment by iMonZ** [comment]
> Fixed... please update.

Hey,
this problem still occurs with the Flagfox extension (the flags are squished)
